services:
  game-service:
    build: ./backend/game_service
    container_name: game-service
    volumes:
      - ./backend/game_service:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    command: npm run dev
    networks:
      - transcendence
    environment:
      - LISTEN_PORT=3000

  matchmaking-service:
    build: ./backend/matchmaking_service
    container_name: matchmaking-service
    volumes:
      - ./backend/matchmaking_service:/app
      - /app/node_modules
      - ./backend/matchmaking_service/data:/app/data
    ports:
      - "3000:3000"
    networks:
      - transcendence
    environment:
      - PORT=${MATCHMAKING_PORT}
      - NODE_ENV=${NODE_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
      - DB_VERBOSE=${DB_VERBOSE}
      - DATABASE_PATH=${MATCHMAKING_DATABASE_PATH}
      - GAME_SERVICE_URL=${GAME_SERVICE_URL}
      - SERVICE_URL=${MATCHMAKING_SERVICE_URL}
    command: npm run dev
    depends_on:
      - game-service

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3004:3000"
    networks:
      - transcendence
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3004/
      - GF_SECURITY_ADMIN_USER=admin1
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOG_LEVEL=debug

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./backend/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - transcendence

volumes:
  grafana-storage: {}

networks:
  transcendence:
    driver: bridge
