openapi: 3.0.0
info:
  title: Webhooks
  version: 0.0.0
tags:
  - name: Matchmaking Service
paths:
  /webhooks/game-result:
    post:
      operationId: MatchmakingService_gameComplete
      description: For tournament games, a winner must be present.
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '400':
          description: The server could not understand the request due to invalid syntax.
      tags:
        - Matchmaking Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GameResultWebhook'
components:
  schemas:
    GameResultWebhook:
      type: object
      required:
        - gameId
        - mode
        - players
        - date
        - duration
      properties:
        gameId:
          type: string
        mode:
          type: string
          enum:
            - classic
            - tournament
        players:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: uint64
              score:
                type: integer
                format: int32
            required:
              - id
              - score
          minItems: 2
          maxItems: 4
        winnerId:
          type: integer
          format: uint64
        date:
          type: string
          format: date-time
        duration:
          type: string
          format: duration
