openapi: 3.0.0
info:
  title: Internal-Only REST APIs
  version: 0.0.0
tags:
  - name: Game Service
paths:
  /internal/games/create:
    post:
      operationId: GameService_newGame
      description: Matchingmaking requests new game.
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewGameResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
        '401':
          description: Access is unauthorized.
      tags:
        - Game Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewGameRequest'
  /internal/games/{gameId}/status:
    get:
      operationId: GameService_getGameStatus
      description: Matchmaking requesting state of a game -> sanity check.
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameStatusReponse'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - Game Service
components:
  schemas:
    FtTranscendence.GameKey:
      type: object
      required:
        - key
        - gameId
        - expires
      properties:
        key:
          type: string
        gameId:
          type: string
        expires:
          type: string
          format: date-time
      description: |-
        `GameKey` is returned by all the endpoints that are opening game websocket connection.
        Since the websocket endpoint cannot have body,
        `GameKey` will be the first message send via the newly established websocket"
    GameStatusReponse:
      type: object
      required:
        - gameId
        - status
      properties:
        gameId:
          type: string
        status:
          type: string
          enum:
            - waiting
            - in_progress
    NewGameRequest:
      type: object
      required:
        - nPlayers
        - gameMode
      properties:
        nPlayers:
          type: integer
          format: uint32
          minimum: 2
          maximum: 4
        gameMode:
          type: string
          enum:
            - classic
            - tournament
    NewGameResponse:
      type: object
      required:
        - gameKeys
      properties:
        gameKeys:
          type: array
          items:
            $ref: '#/components/schemas/FtTranscendence.GameKey'
          minItems: 2
          maxItems: 4
